from modules.auto_model import AutoModel
from modules.qwen_vl_model import QwenVLModel
from modules.qwen_vl2_model import QwenVL2Model
from modules.gguf_model import GGUFModel
from modules.minicpm_v_model import MiniCPMModel
from modules.phi_vision_model import PhiVisionModel
from modules.llava_one_vision_model import LlavaOneVisionModel
from modules.internvl2_model import InternVL2Model